### ISSUE TITLE
Is there a way to achieve updateMatchRules / switchStandbyMatchIndexToLive?

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-deployment-tooling#30]
### Background on the problem the feature will solve/improved user experience
I have a connector which is correctly delivering a link chart to the i2 desktop client but the web ui. It consists of a person with links out to other people, locations, phone numbers etc. Works fine.

On the Analyze web client I'm getting a No Label entity at the centre of the chart and the person and all the other entities are linked to it.

On a normal Analyze deployment we've done
setup -t updateMatchRules
setup -t switchStandbyMatchIndexToLive

to resolve this. But I can't figure out how to apply that in the containers version of i2 Analyze.

**Comment by Anthony-Johnson-i2** [comment]
Hi @bohdanszymanik  

If you update your system-match-rules.xml as usual and then run` deploy` the software should detect what has changed and  handle  things.

Cheers
