### ISSUE TITLE
Can't install Connector Designer

### ISSUE THREAD

**Issue by lisandrosUnitech** [i2group/analyze-deployment-tooling#31]
Hello,

We have a Red Hat Enterprise Linux release 8.10 (Ootpa) Server in which we're trying to install Connector Desginer.

We are following the steps in this link https://docs.i2group.com/analyze/4.4.4/deploy_connector_designer.html.

But we're having an issue trying to execute the command install-connector-designer on step 8.

In a certain moment the console throw me the next error message:

"
[root@msm-i2anbp-desa-db analyze-deployment-tooling-main]# ./install-connector-designer
latest: Pulling from i2group/i2eng-analyze-containers-client
Digest: sha256:bb4fc064fc5d1896cb40957095cb01901c81a452b62f987e6b4d59652ff440b5
Status: Image is up to date for i2group/i2eng-analyze-containers-client:latest
[docker.io/i2group/i2eng-analyze-containers-client:latest](http://docker.io/i2group/i2eng-analyze-containers-client:latest)
Using the latest version: 3.0.0
3.0.0: Pulling from i2group/i2eng-analyze-containers-client
Digest: sha256:bb4fc064fc5d1896cb40957095cb01901c81a452b62f987e6b4d59652ff440b5
Status: Image is up to date for i2group/i2eng-analyze-containers-client:3.0.0
[docker.io/i2group/i2eng-analyze-containers-client:3.0.0](http://docker.io/i2group/i2eng-analyze-containers-client:3.0.0)
sqlserver JDBC driver version 12.6.0 already exists.
postgres JDBC driver version 42.7.2 already exists.

#----------------------------------------------------------------------
# Installing connector-designer
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# Setting up i2 Analyze Minimal Toolkit
#----------------------------------------------------------------------
mkdir: cannot create directory ‘/opt/analyze-deployment-tooling/pre-reqs/i2analyze’: Permission denied
[root@msm-i2anbp-desa-db analyze-deployment-tooling-main]#

"

![image](https://github.com/user-attachments/assets/975eafea-c8d4-4d52-b70e-d31726263f05)

I looked into that path to see if the directory was created but it didn't. Also I checked the permissions in the i2analyzeMinimal.tar.gz, install-pre-reqs.bat files and the user root has all of it.

I don't know what else I could look or seach into to resolve this issue.

The doubts I've got is, why the command install-connector-designer is throwing me this error and how can I fix it?

I hope I've been as clear as possible.

Kind regards,
Lisandro.

**Comment by Ariana-Hlavaty-i2** [comment]
Hi Lisandro,

We do not support root user. You will need to delete the installation and rerun the script with a non-root user.

**Comment by lisandrosUnitech** [comment]
Hi Ariana,

Thank you for your reply.

Is there a command to execute to delete the installation or how should I proceed?

**Comment by Ariana-Hlavaty-i2** [comment]
Hi Lisandro,

There is no command. Please delete the analyze-deployment-tooling-main folder and download again with a non-root user. 
Alternatively, you could run `chown -R <non-root-user-name> analyze-deployment-tooling-main` (replace with the name of your user), login with your non-root user and rerun the script.

**Comment by lisandrosUnitech** [comment]
Hello Ariana,

Thank you very much, I understand.

I was finally able to install Connector Designer. I needed to make other configurations before I could install it but in the end I was able to do it.

Thanks for your support.

This would be all for the moment, if I have any other questions I will raise a new ticket.

Kind regards,
Lisandro.
