### ISSUE TITLE
Connector Designer. Know How: delete connector containers

### ISSUE THREAD

**Issue by lisandrosUnitech** [i2group/analyze-deployment-tooling#33]
Hi,

Just a quick question.

We were testing Connector Designer and we were able to create connectors which search public APIs.

We created several test connector containers and the question we had is how we can delete these containers that we created in our tests.

![image](https://github.com/user-attachments/assets/90647b45-d8be-4d88-9289-34b0e6444012)

I understand that one way would be to delete the folder that contains the containers we created and reinstall Connector Designer. But I wanted to know if there is another way to do this without having to reinstall the tool.

I hope I have been as clear as possible.

Kind regards,
Lisandro.

**Comment by Anthony-Johnson-i2** [comment]
Hi @lisandrosUnitech 

It is good to see that you are actively using this.

Connector containers do get left behind after UI deletion, as you have seen,  but manual deletion of the folders can be problematic and should be avoided.

Connector Designer is a fully supported part of our product suite,  and as such, questions or issues about its use are best served  by using the well established official support route.  (It is not really a part of analyze-deployment-tooling).

Please [raise a ticket](https://i2group.com/support-request)  in the usual way and we can help you through our official product support route.

Cheers

**Comment by Anthony-Johnson-i2** [comment]
Thank you for raising a ticket @lisandrosUnitech for this, it is much appreciated.

**Comment by lisandrosUnitech** [comment]
Hi Anthony,

i2 Support told me the steps to take to delete a connector.

Instructions:

1. From the Connector Designer Homepage, i.e. the list of connectors, click on the connector you would like to delete.
2. Click the Edit button to go into edit mode.
3. Click the Delete button, displayed as a trash can icon.
4. In the Delete connector dialog, click Delete to confirm your decision.

This will be all for now.

Sorry for the delay in answer and close this issue.

Kind regards,
Lisandro
