### ISSUE TITLE
analyse-deployment-tooling bootstrap script fails due to permission denied

### ISSUE THREAD

**Issue by max-schuller5** [i2group/analyze-deployment-tooling#34]
**Describe the bug**

When running the bootstrap script for analyse-deployment-tooling I get the following error

```
#----------------------------------------------------------------------
# Running generate-secrets
#----------------------------------------------------------------------
cp: failed to preserve ownership for '/opt/analyze-deployment-tooling/environment-secrets/generated-secrets/certificates/CA/x509.ext.template': Permission denied
```

**To Reproduce**
Following this guide https://i2group.github.io/analyze-deployment-tooling/content/getting_started.html
1. download the `analyse-deployment-tooling 3.0.0`
2. Extract from tar.gz and rename folder to `analyse-deployment-tooling`
3. Modified hosts file
4. add i2analyzeMinimal-4.4.4.0-GM.tar.gz to pre-reqs and rename to i2analyzeMinimal.tat.gz

**Expected behavior**
Script should finish successfully

**Screenshots**
<img width="865" alt="Screenshot 2024-09-09 at 3 44 56 PM" src="https://github.com/user-attachments/assets/c43d28c4-dac2-458a-9755-f4b022811238">

**Hardware and Software information**

- OS: Mac Apple M2 Pro
- Version: 14.6.1 
- i2 Analyze version: 4.4.4
- Environment type: pre-prod
- Deployment pattern: don't know

**Additional context**
I can't change the permission manually on the files because they reset each time the script is run

**Comment by Anthony-Johnson-i2** [comment]
Hi @max-schuller5  I had a chat with someone who has this set up on their Mac and for them it is working as expected. 

They ask if you could please let us know 

>  The output of whoami 
>  The permissions on /users/max.schuller 
>  The exact command that you ran

 
 Thank You

**Comment by max-schuller5** [comment]
The output of whoami is `vscode`
Permissions are shown below
<img width="492" alt="Screenshot 2024-09-10 at 8 57 01 AM" src="https://github.com/user-attachments/assets/25a94b89-aef1-4d31-88fa-7261028a69b8">
I ran `./bootstrap`

**Comment by Anthony-Johnson-i2** [comment]
Hi @max-schuller5  

I fed this back to our development team and as they are not seeing what you are seeing here they have the following suggestions to try and resolve this.

1. Delete the installation and redownload. (It might have been that the devcontainer wasn't correctly configured the first time the bootstrap was run).
2. Alternatively run bootstrap from outside the devcontainer (in a Mac Terminal).  (That will still require the current installation to be deleted).

Cheers

**Comment by max-schuller5** [comment]
Thanks @Anthony-Johnson-i2 running deleting and redownloading did not work but running it in a mac terminal has allowed me to get passed this roadblock. I am now encountering another issue. The data base will not start, I can start `schema_dev` and `i2c` but not `i2c_istore`

```
#----------------------------------------------------------------------
# Deployment Information:
#----------------------------------------------------------------------
ANALYZE_CONTAINERS_ROOT_DIR: /opt/analyze-deployment-tooling
CONFIG_NAME: config-development
DEPLOYMENT_PATTERN: i2c_istore
DB_DIALECT: sqlserver
I2A_DEPENDENCIES_IMAGES_TAG: 4.4.4.0
```
```
#----------------------------------------------------------------------
# Stopping connector containers for other configs
#----------------------------------------------------------------------

WARN: File /opt/analyze-deployment-tooling/path-configuration.json does not contain shared configurations. Skipping.
```
```
#----------------------------------------------------------------------
# Waiting for SQL Server to be live
#----------------------------------------------------------------------
chown: changing ownership of '/opt/databaseScripts/generated/dynamic': Permission denied
chown: changing ownership of '/opt/databaseScripts/generated/.DS_Store': Permission denied
chown: changing ownership of '/opt/databaseScripts/generated/static': Permission denied
chown: changing ownership of '/opt/databaseScripts/generated': Permission denied
SQL Server is NOT live (attempt: 1/30). Waiting...
```

**Comment by Anthony-Johnson-i2** [comment]
Hi @max-schuller5  you still have permissions oddities that we do not see.

Can you check that you are on the latest Docker Desktop version (>4.32.0) and VSCode (>1.92) please.

For clarity, in your original comment  is 14.6.1 referring to MacOS Sonoma?

After the bootstrap you should open vscode and the devcontainer and work from there again,  apologies if you have already done this, as we do not support running the deploy commands from a Mac terminal.

Given the installation is now done, inside the devcontainer can you  run

`chown -R vscode:vscode /Users/max.shuller/analyze-deployment-tooling `

 and try the deploy command again please.

Cheers

**Comment by max-schuller5** [comment]
HI @Anthony-Johnson-i2 I believe I have identified the root of the problem. I am using Colima and not Docker Desktop. Colima seems to handle privileges differently to Docker.

**Comment by Anthony-Johnson-i2** [comment]
Hi @max-schuller5  I think you are correct.

If only I had asked the docker desktop question earlier :-)

We do not support using Colima unfortunately.

**Comment by max-schuller5** [comment]
Thanks for your help @Anthony-Johnson-i2, closing this ticket
