### ISSUE TITLE
Prometheus is not live 

### ISSUE THREAD

**Issue by max-schuller5** [i2group/analyze-deployment-tooling#35]
**Describe the bug**
Prometheus will not connect
If I ignore certs by running
```
curl -u prometheus:8NlHg1KBqBHKESeiAWoUEw== -k https://prometheus.eia:9090/-/healthy
```
it returns "Prometheus Server is Health"

**To Reproduce**

1. Have set up analyse-deployment-toolkit
2. run ./scripts/deploy

```
#----------------------------------------------------------------------
# Waiting for Prometheus to be live
#----------------------------------------------------------------------
Prometheus is NOT live (attempt: 1/30). Waiting...
Prometheus is NOT live (attempt: 2/30). Waiting...
Prometheus is NOT live (attempt: 3/30). Waiting...
Prometheus is NOT live (attempt: 4/30). Waiting...
Prometheus is NOT live (attempt: 5/30). Waiting...
Prometheus is NOT live (attempt: 6/30). Waiting...
Prometheus is NOT live (attempt: 7/30). Waiting...
Prometheus is NOT live (attempt: 8/30). Waiting...
Prometheus is NOT live (attempt: 9/30). Waiting...
Prometheus is NOT live (attempt: 10/30). Waiting...
Prometheus is NOT live (attempt: 11/30). Waiting...
```

**Expected behavior**
Prometheus should be live

**Hardware and Software information**
Fill in the following information:
I'm running it in an ec2 box

- OS: Linux ubuntu
- Version: ubuntu-noble-24.04-amd64-server
- i2 Analyze version: 4.4.4
- Environment type: config-dve
- Deployment pattern: i2c_cstore

**Additional context**

**Comment by max-schuller5** [comment]
it was because of snap package manager

**Comment by Anthony-Johnson-i2** [comment]
Excellent news. I saw an email notification for this when I got in this morning and you had already sorted it :-)
