### ISSUE TITLE
Issue using Connector Designer with my custom REST Endpoint

### ISSUE THREAD

**Issue by LeonardoCCouto** [i2group/analyze-deployment-tooling#38]
**Describe the bug**
When I try creating a connector with my endpoint I get the following message: "The request received no response. Check the endpoint URL and try again.‬", but nothing shows on the connector container log, or the liberty container log. So I don't have specific information on why it did not work.

**To Reproduce**
Try to configure a new connector using as endpoint a custom REST (no auth) webservice (Linda from i2 Support has the link for the specific endpoint if a direct test is desired).

**Hardware and Software information**
Fill in the following information:

- OS + version: Windows 11+ WSL 2 (ubuntu)
- Architecture: Intel 64
- Software Version: 3.0.1
- Docker version: Docker version 27.2.0, build 3ab4256
- VS Code version: 1.94
- Environment type: dev
- Deployment pattern: istore

**Additional context**
I was able to use the designer consuming an open endpoint (https://viacep.com.br/ws/01001000/json).

but when I try consuming another endpoint it just returns me the following message: "The request received no response. Check the endpoint URL and try again.‬". I was able to test the connection to the endpoint using curl inside the connector_designer.dev_4.4.4 container, and also put my endpoint cert inside the additional-trust-certificates.cer file and redeployed the solution, but I still get the same error.

Is there any log where I can get a more detailed message on why the WS is not being consumed?

**Comment by Oleksandr-Kushchak-i2** [comment]
Hi @LeonardoCCouto,

To allow connectors to access external data sources, you must specify the allowed hosts. You can find information on how to configure it in the [Configuring Connector Designer](https://docs.i2group.com/analyze/4.4.4/deploy_connector_designer.html) section. 

Let us know if that resolves the issue.

**Comment by LeonardoCCouto** [comment]
I did the allowed hosts config beforehand, and was able to connect to other external hosts, but this specific one is not working, and I don't know why. I even tried adding the ssl cert to the additional-trust-certificates.cer, but the same issue still occurs.

**Comment by Anthony-Johnson-i2** [comment]
Hi @LeonardoCCouto  

Connector Designer is part of the i2 Analyze product offering  so as this seems to be a Connector Designer related issue rather than an ADT issue you should raise a support ticket  [here](https://i2group.com/support-request) so that this can be handled through the official support route. 

If you reference this issue that should save you repeating what you have already done here.

Cheers

**Comment by LeonardoCCouto** [comment]
Thank you, the ticket was already up, and I will follow up with them.
Kindest,

**Comment by Anthony-Johnson-i2** [comment]
Closing this issue.

This was investigated via a support ticket and found to be a CORS (Cross Origin Resource Sharing) issue and the case raised has been closed.

Cheers
