### ISSUE TITLE
Failed to deploy Connector Designer

### ISSUE THREAD

**Issue by jubba2001** [i2group/analyze-deployment-tooling#39]
The following error occurs when running the "./install-connector-designer" command:
```
...

#----------------------------------------------------------------------
# Adding environment variable resolution support
#----------------------------------------------------------------------
cp: cannot create regular file '/opt/analyze-deployment-tooling/images/sql_client/db-scripts/environment.sh': Permission denied
```

**To Reproduce**

1. Run script `sudo ./install-connector-designer -v`
2. See error
3.  Run `ls /opt/analyze-deployment-tooling`
4.  No such file or directory

**Hardware and Software information**

- OS + version: [Oracle Linux Server 8.10]
- Architecture: [x64]
- Software Version: [v3.0.1]
- Docker version: [26.1.3]
- VS Code version: [-]
- Environment type: [config-dev]
- Deployment pattern: [-]

**Additional context**

We are trying to [deploy Connector Designer] (https://docs.i2group.com/analyze/4.4.4/deploy_connector_designer.html)

**Comment by Oleksandr-Kushchak-i2** [comment]
Hi @jubba2001,

You shouldn't need `sudo` to run `./install-connector-designer -v`.

The following directory  `/opt/analyze-deployment-tooling`  and all of its content should be owned by the non-root user.

We are aware that the documentation for setting up Linux environment is mising and the next release will include this information.

In the meantime I would suggest you start from scratch ensuring you run all commands with the the user you set up (not `root`) and without using `sudo`.

**Comment by jubba2001** [comment]
The next error:
```
error: exec: "/opt/analyze-deployment-tooling/utils/containers/check-installers"
: stat /opt/analyze-deployment-tooling/utils/containers/check-installers: nosuch file or directory
```
There is no folder `/analyze-deployment-tooling/utils/` in release 3.01

**Comment by jubba2001** [comment]
Sorry, my mistake. I added `sudo`  trying to avoid the "_permission denied while trying to connect to the Docker daemon socket_" error.

All I had to do was grant the current user to create docker containers: `sudo usermod -aG docker $USER`.

Please, add this to the documentation as well.

**Comment by jubba2001** [comment]
Sorry, my mistake. I added `sudo`  trying to avoid the "_permission denied while trying to connect to the Docker daemon socket_" error.

All I had to do was grant the current user to create docker containers: `sudo usermod -aG docker $USER`.

Please, add this to the documentation as well.
