### ISSUE TITLE
Wrapper

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-deployment-tooling#41]
**Describe the bug**
I try to create a wrapper script to start to container from outside VSCode and follow this manual, https://i2group.github.io/analyze-deployment-tooling/content/tools-and-functions/wrappers.html.

**To Reproduce**
One of my configs is running in i2 analyze.
![image](https://github.com/user-attachments/assets/706511b9-dd0a-42fb-8a0d-e190c1c3234a)

In a new terminal I tried the following commands.
![image](https://github.com/user-attachments/assets/29f59ded-7e69-42c5-93ad-e692f29e5e36)

**Hardware and Software information**
Fill in the following information:

- OS + version: Windows 10
- i2 Analyze 4.4.4 fp 3
- Software Version: v3.0.0
- Docker version: 27.3.1
- VS Code version: 1.95.3
- Environment type: config-dev
- Deployment pattern: i2c_istore

**Additional context**
Content of the script folder
![image](https://github.com/user-attachments/assets/c2237798-0b95-49a4-be3b-c47555e30435)

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @stvdo, thanks for making us aware of this bug.

There is a typo in the docs.

Please run the following instead:
```
./run-util-script install-wrappers -p /home/sdor/wrappers
```

Many Thanks,
Ariana

**Comment by stvdo** [comment]
Hi Ariana,

Thanks for your quick response!

That works better, thank you! 

However somehow the wrapper folder is not created. What do I do wrong?
![image](https://github.com/user-attachments/assets/768c5b39-bf7c-4807-9a46-35594e97d33a)

**Comment by Ariana-Hlavaty-i2** [comment]
You shouldn't have a "./" since that means relative. Try instead `cd /home/sdor/wrappers` for the absolute path.

If this doesn't work, please add the `-v` flag to the command to get more information

**Comment by stvdo** [comment]
The wrappers folder is not created.
![image](https://github.com/user-attachments/assets/f7dddbc2-f4ca-4a6b-a46a-e1f43163d991)

**Comment by Ariana-Hlavaty-i2** [comment]
can you please add the `-v` flag when running the command?

```
./run-util-script install-wrappers -p /home/sdor/wrappers -v
```

**Comment by stvdo** [comment]
![image](https://github.com/user-attachments/assets/46ff6c49-9db7-4f2e-8245-c6e0ee96a5c5)

**Comment by Ariana-Hlavaty-i2** [comment]
Thanks for the information.

We will attempt to reproduce locally and get back to you with an answer.

**Comment by stvdo** [comment]
I replaces the code on line 94
![image](https://github.com/user-attachments/assets/d35059fe-91bc-4985-81c0-64c32a8836f5)

After running the install-wrappers command I get this error.
/home/sdor/analyze-deployment-tooling-300/install-wrappers: line 120: /home/sdor/wrappers/scripts/.analyze_containers_root_dir.conf: No such file or directory

![image](https://github.com/user-attachments/assets/b5578a1e-e1b0-4c9c-9a24-58aa746bc797)

**Comment by stvdo** [comment]
it is owned by my user, also the content of the folder.

![image](https://github.com/user-attachments/assets/a37d5998-15ab-4e8d-94a2-3c9d765cf877)

**Comment by Ariana-Hlavaty-i2** [comment]
@stvdo I can see in the previous screenshot that you ran the install-wrappers script inside VSCode with the vscode user. The script needs to be run outside the dev container with your local user. 

We are not able to reproduce it on our side by running the script from a new terminal outside VSCode.

If rerunning the script from outside VSCode doesn't fix the issue then you can run the following commands to add the missing file:
```
export ANALYZE_CONTAINERS_ROOT_DIR="/home/sdor/analyze-deployment-tooling-300"
echo "ANALYZE_CONTAINERS_ROOT_DIR=${ANALYZE_CONTAINERS_ROOT_DIR}" >"/home/sdor/wrappers/scripts/.analyze_containers_root_dir.conf"
```

**Comment by stvdo** [comment]
@Ariana-Hlavaty-i2 thanks lot, running this outside VSCode fixed the issue indeed!
