### ISSUE TITLE
Connector URL changed after updating

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-deployment-tooling#42]
**Describe the bug**
I updated the BAG connector from 1.3 to 1.4. The connector was running without issues, but after the update i2 Analyze can't find the config.

**To Reproduce**
1. Create new package
2. Upload this package to i2 Analyze
3. Change the version to 1.4.0 of the connector-version.json
4. Remove the certificates from the bag-connector
5. Run manage-environment -t connectors
6. Deploy the config again

**Expected behavior**
The correct URL to the config in the admin console.

**Screenshots**
The container is running
![image](https://github.com/user-attachments/assets/7f01b8a6-76ed-4b08-9ea6-58a027b19587)

The admin console, the BAG connector has a different URL of the config somehow.
![image](https://github.com/user-attachments/assets/147df7b6-2f4f-4d19-89dd-53af0128fe72)

Settings
![image](https://github.com/user-attachments/assets/979197a3-974a-40f7-98c0-08f285c36f00)

**Hardware and Software information**
 - OS: Windows 10
 - Version: 
 - i2 Analyze version: 4.4.4 FP3
 - Database dialect: postgres
 - Configuration mod (Optional): 

**Additional information**
The link in the documentation isn't available, https://i2group.github.io/analyze-connect-node-sdk/guide/walkthrough/8-packaging-and-distribution.html. 
![image](https://github.com/user-attachments/assets/d0f88861-0d09-420b-a645-9d3df4c24864)
Should link to https://i2group.github.io/analyze-deployment-tooling/content/connector_config_dev.html

I copied the Dockerfile and docker-entrypoint.sh from template folder to be sure that I use the latest version.

I did not do a clean deploy yet to prevent importing the data again in the Information Store.

**Comment by Anthony-Johnson-i2** [comment]
Re-pinging you @stvdo Steven from the new location of the issue to be sure you can see where it is.

**Comment by stvdo** [comment]
@Anthony-Johnson-i2 thank you for your response!

Adding the userManaged: false to the connector-definition.json fixed the issue indeed. Maybe it's good to add a more clear error when that setting is missing in the connector-definition. Now you're looking in the wrong direction.

Can it be that the default value was true in a previous version of i2 Analyze? Because I had no issues a few month ago with the same settings.

**Comment by Anthony-Johnson-i2** [comment]
Thanks for the feedback @stvdo I'll let the team know and will ask if the default for userManaged has changed.

Cheers

**Comment by stvdo** [comment]
Hi @Oleksandr-Kushchak-i2 thanks a lot. Good to know this shouldn't be the issue.

However it's weird that the 'manage-environment -t connectors' didn't fix it, and changing the connector-definition.json fixed it.
