### ISSUE TITLE
Symbolic links doesn't work after update to 3.0.1

### ISSUE THREAD

**Issue by stvdo** [i2group/analyze-deployment-tooling#45]
**Describe the bug**
I use the shared config. This worked fine till I updated yesterday to the ADT 3.0.1. Is this something wrong in the ADT or in my local setup? My config is not changed, so I assume it's an issue in the ADT.

![image](https://github.com/user-attachments/assets/e1af2217-726a-4e6b-8c86-fd01834bbf35)

i2 Analyze is running without issues, the only thing is that I have to change my config in another window.

![image](https://github.com/user-attachments/assets/2702d2de-f75b-458a-a4b0-9888abb66ee8)

**Hardware and Software information**
 - OS: Windows
 - Version: 3.0.1
 - i2 Analyze version: 4.4.4 FP 3

**Comment by Oleksandr-Kushchak-i2** [comment]
Hi,

This can happen if your `.devcontainer/devcontainer.json` file doesn't have the bind mount for the shared-config repo.
To debug this further we will need to see the content of the `path-configuration.json`  and the `.devcontainer/.devcontainer.json` files. 

Do you have access to the shared config path inside the devcontainer?

**Comment by stvdo** [comment]
Thanks for your quick response.

No I can't access home/sdor/de-demo-configurations.
![image](https://github.com/user-attachments/assets/1e0857af-cd90-415a-a16b-3591c8912946)

```
{
  "__comment__": "The analyze containers are located at /home/sdor/analyze-containers/. Insite the de-demo-configuration I checked out the Bitbucket repo, the name of this folder is the path variable.",
  "sharedConfigurations": {
    "rootDirectory": "/home/sdor/de-demo-configurations",
    "repositories": [
      {
        "path": "analyse-studio-demo-config"
      }
    ]
  }
}
```

and 

```
{
  "name": "Analyze Containers Dev",
  "image": "i2group/i2eng-analyze-containers-dev:1.2",
  "remoteUser": "vscode",
  "runArgs": [
    "--init",
    "--env-file",".devcontainer/devcontainer.env"
  ],
  "mounts": [
    "source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind",
    "source=analyze-containers,target=/commandhistory,type=volume",
    "source=${localEnv:HOME}/.m2,target=/home/vscode/.m2,type=bind,consistency=cached",
    "source=${localEnv:HOME}/.config/gh,target=/home/vscode/.config/gh,type=bind",
    "source=${localEnv:HOME}/.jfrog,target=/home/vscode/.jfrog,type=bind"
  ],
  "overrideCommand": false,
  "initializeCommand": "bash ./.devcontainer/bootstrap init",
  "onCreateCommand": "bash ./.devcontainer/bootstrap create",
  "postStartCommand": "bash ./.devcontainer/bootstrap start",
  "remoteEnv": {
    "WORKSPACE": "${containerWorkspaceFolder}",
    "DEVCONTAINER": "true",
    "HOST_HOME": "${localEnv:HOME}",
    "DOCKER_BUILDKIT": "1"
  },
  "workspaceMount": "source=${localWorkspaceFolder},target=${localWorkspaceFolder},type=bind,consistency=cached",
  "workspaceFolder": "${localWorkspaceFolder}",
  "customizations": {
    "vscode": {
      "extensions": [
        "ms-azuretools.vscode-docker",
        "redhat.vscode-yaml",
        "redhat.vscode-xml",
        "ms-vscode-remote.remote-wsl",
        "vscjava.vscode-java-pack",
        "vscode-icons-team.vscode-icons"
      ],
      "settings": {
        "remote.autoForwardPorts": false
      }
    }
  }
}
```

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @stvdo,

We can see that you are indeed missing the bind mount. This shouldn't have happened during an upgrade so we will try to investigate from our side.

To fix the issue, please follow the steps in the docs to reconfigure your shared configurations as per https://i2group.github.io/analyze-deployment-tooling/content/managing_shared_configurations.html#configuring-your-shared-repositories-location

**Comment by stvdo** [comment]
Hi @Ariana-Hlavaty-i2, 

Thanks a lot, that fixed it indeed. If this isn't touched during the upgrade it should be something on my site.
