### ISSUE TITLE
ILLEGAL STATE: The new security schema has incompatible differences with the existing one

### ISSUE THREAD

**Issue by bohdanszymanik** [i2group/analyze-deployment-tooling#46]
### I think this is a misunderstanding on my behalf
I'm trying to modify the security schema using the update security schema walkthorough: https://i2group.github.io/analyze-deployment-tooling/content/walkthroughs/update_security_schema.html

My new security-schema.xml in examples/pre-prod/walkthroughs/change-management/configuration-changes looks like the following. Note that I've removed dimension SD-SC. I have a dimensions and permissions that look like this:

	<SecurityDimensions Id="812fb036-dd9b-4190-bf9e-fd89c01f84d6" Version="1">
		<AccessSecurityDimensions>
			<Dimension Id="SD-SL" DisplayName="Security Level" Description="Security Level" Ordered="true">
				<DimensionValue Id="INCONF" DisplayName="INCONFIDENCE" Description="INCONFIDENCE"/>
				<DimensionValue Id="UNCLASS" DisplayName="UNCLASSIFIED" Description="UNCLASSIFIED"/>
			</Dimension>
		</AccessSecurityDimensions>
	</SecurityDimensions>

	<SecurityPermissions>
		<GroupPermissions UserGroup="MYTESTAPP">
			<Permissions Dimension="SD-SL">
				<Permission DimensionValue="INCONF" Level="UPDATE" />
				<Permission DimensionValue="UNCLASS" Level="UPDATE" />
			</Permissions>
		</GroupPermissions>
	</SecurityPermissions>

	<DefaultSecurityDimensionValues>INCONF</DefaultSecurityDimensionValues>

I'm getting the following error after running updateSecuritySchemaWalkthrough.sh
![image](https://github.com/user-attachments/assets/3d93261e-1324-4dbf-bb60-4eb84c7fd701)

Is removing SD-SC here not possible? I had previously used this security schema successfully with the config dev environment.

**Comment by bohdanszymanik** [comment]
I noticed that if I add in SD-SC then it proceeds but I don't understand how to remove an existing security dimension.

**Comment by Anthony-Johnson-i2** [comment]
Hi @bohdanszymanik 

You can not update a deployed (in use) security schema with a new one with a deleted security dimension as this is classed as a destructive change.

This documents security schema changes and their repercussions.

https://docs.i2group.com/analyze/4.4.4/security_schema_modify.html

After a destructive change in a standard Analyze deployment with an info store you would need to recreate the database and repopulate the schemas usually by redeploying. @Ariana-Hlavaty-i2 or @Oleksandr-Kushchak-i2 can you link to the steps for that in this environment please.


Cheers

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @bohdanszymanik @Anthony-Johnson-i2,

We don't have walkthrough documentation to apply destructive schema changes in pre-prod. The pre-prod environment is meant as an example only for the Reference Architecture and replicates a production deployment where data cannot be lost.

To develop your schemas you would use the Config Dev Environment (destructive changes are allowed here) and then deploy it to your other environments following the Ref. Architecture.

**Comment by bohdanszymanik** [comment]
Ah - I was thinking that might be the case. Not a problem now I know why.

Thanks
