### ISSUE TITLE
Wrong Path used when trying to upgrade

### ISSUE THREAD

**Issue by Timon-IW** [i2group/analyze-deployment-tooling#47]
**Describe the bug**
When I want to upgrade my current installation with the "./bootstrap" command it uses the wrong path, it installs everything correct in the right path, but when asked if I would like to upgrade it says not valid path.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/da2de901-9f0d-49cc-985c-6cce90bb2601)

I hope that this is sufficient information, and I apologize for not providing the other ones.

**Comment by Ariana-Hlavaty-i2** [comment]
Hi @Timon-IW,

Apologies for the confusion.

Please follow the steps in https://i2group.github.io/analyze-deployment-tooling/content/managing_upgrade_env.html. You need to download the new release into a different folder (e.g. analyze-deployment-tooling-3.0.2) then proceed with the upgrade.

**Comment by Timon-IW** [comment]
Hi @Ariana-Hlavaty-i2,

Thanks for the swift reply.
I didn't see that the upgrade process is this much extra work even within the same major version.
After I followed the documentation you provided, everything is working again.
But it would be better if it told me that when I tried to upgrade.

Best Regards,
Timon
